- hosts: worker
  tasks:
    - name: PHP | Install PHP Modules
      become: yes #untuk menjadi superuser
      apt: pkg={{ item }} state=latest
      tags: common       
      with_items:
        - php7.2-cli
        - php7.2-curl
        - php7.2-mysql
        - php7.2-fpm
        - php7.2-mbstring
        - php7.2-xml
