- hosts: worker
  tasks:
    - name: PHP | Install Ondrej PHP PPA
      become: yes #untuk menjadi superuser
      apt_repository: repo='ppa:ondrej/php' update_cache=yes
    - name: PHP | Install PHP 7.2
      become: yes #untuk menjadi superuser
      apt: pkg=php7.2 state=latest
      tags: ['common']
